### ISSUE TITLE
Allow calculated values in patterns based on question answers

### ISSUE THREAD

**Issue by coordt** [callowayproject/project-forge#19]
### Is your feature request related to a problem? Please describe.

For example, in choosing a license, the pattern might provide the initial choice, but then will want to add additional data based on that choice, like "SPDX", and "license_text".

### Describe the solution you'd like.

Provide an `additional_context` attribute to the `Choice`

```toml
[[questions]]
name = "license"
prompt = "Under what license is this code published?"
type = "str"
choices = [
    { label = "2-Clause BSD License", value = "_bsd-2.jinja", additional_context = [{ spdx = "BSD-2-Clause" }] },
]
```
